In [1]:
# pip install Faker
from faker import Faker

In [4]:
fake = Faker()

names = [fake.name().split() for i in range(100)]
names = [name for name in names if len(name) == 2]
names

[['Jason', 'Gutierrez'],
 ['Thomas', 'Hopkins'],
 ['Morgan', 'Zhang'],
 ['Jeffrey', 'Kennedy'],
 ['Kathryn', 'Miller'],
 ['Thomas', 'Berry'],
 ['Ann', 'Calderon'],
 ['Chad', 'House'],
 ['Tracy', 'Cruz'],
 ['Pamela', 'Fisher'],
 ['Rebecca', 'Mcclain'],
 ['Lisa', 'Simmons'],
 ['Jasmine', 'Mueller'],
 ['Timothy', 'Patterson'],
 ['Darren', 'Leonard'],
 ['Rodney', 'Kim'],
 ['Pamela', 'Wilcox'],
 ['Jose', 'Rogers'],
 ['Michael', 'Wallace'],
 ['Carrie', 'Nguyen'],
 ['Rebecca', 'Johnson'],
 ['Daniel', 'Shannon'],
 ['Dale', 'Mcdonald'],
 ['Jorge', 'Mooney'],
 ['Danielle', 'Fuentes'],
 ['Carolyn', 'Shepherd'],
 ['Travis', 'Parks'],
 ['Christina', 'Sparks'],
 ['Brian', 'Baldwin'],
 ['Jo', 'Chan'],
 ['George', 'Miller'],
 ['Kevin', 'Robbins'],
 ['Ryan', 'Peterson'],
 ['Anne', 'Anderson'],
 ['Steven', 'Thomas'],
 ['Henry', 'Glover'],
 ['Ashley', 'Barnes'],
 ['John', 'Fisher'],
 ['William', 'Roth'],
 ['Christopher', 'Rodriguez'],
 ['Kenneth', 'Mann'],
 ['Jose', 'Anderson'],
 ['Christopher', 'Miller'],
 ['Nicole', 'Davis'],
 ['Ashley', 'Alvarado'],
 ['Kathy', 'Herring'],
 ['Joy', 'Hobbs'],
 ['William', 'Lawrence'],
 ['Brian', 'Rodriguez'],
 ['Brandon', 'Martin'],
 ['Ricky', 'Peters'],
 ['Jeffrey', 'Rogers'],
 ['Candace', 'Barajas'],
 ['Lee', 'Huynh'],
 ['Laura', 'Farmer'],
 ['Michael', 'Herring'],
 ['Caitlyn', 'Thompson'],
 ['Kimberly', 'Harper'],
 ['Jessica', 'Williams'],
 ['Tommy', 'Simmons'],
 ['Sheila', 'Bell'],
 ['Brandon', 'Perez'],
 ['Kevin', 'Collier'],
 ['Angela', 'Evans'],
 ['Xavier', 'Johnson'],
 ['Stacy', 'Frost'],
 ['Nancy', 'Jones'],
 ['Joseph', 'Drake'],
 ['Francisco', 'Sanford'],
 ['Stephanie', 'Gonzalez'],
 ['Linda', 'White'],
 ['Thomas', 'Douglas'],
 ['Catherine', 'Williams'],
 ['Maurice', 'Martin'],
 ['James', 'Evans'],
 ['Austin', 'Garcia'],
 ['Drew', 'Cooper'],
 ['Brittany', 'Cunningham'],
 ['Amanda', 'Nelson'],
 ['Bryan', 'Fields'],
 ['Rebecca', 'Dyer'],
 ['Gabriel', 'Green'],
 ['Alejandra', 'Fernandez'],
 ['Leonard', 'Clayton'],
 ['Troy', 'Thomas'],
 ['Kristina', 'Solomon'],
 ['Courtney', 'Robbins'],
 ['Joseph', 'Clark'],
 ['Leah', 'Wright'],
 ['Haley', 'Williams']]

In [8]:
import sqlite3
connection = sqlite3.connect('first_sample.db')

In [9]:
insert_query = 'INSERT INTO people(name, surname) VALUES(?, ?)'
cursor = connection.cursor()
for name in names:
    cursor.execute(insert_query, name)
connection.commit()

In [11]:
select_query = 'select *from people'
for i in cursor.execute(select_query):
    print(i)

(1, 'Jason', 'Gutierrez')
(2, 'Thomas', 'Hopkins')
(3, 'Morgan', 'Zhang')
(4, 'Jeffrey', 'Kennedy')
(5, 'Kathryn', 'Miller')
(6, 'Thomas', 'Berry')
(7, 'Ann', 'Calderon')
(8, 'Chad', 'House')
(9, 'Tracy', 'Cruz')
(10, 'Pamela', 'Fisher')
(11, 'Rebecca', 'Mcclain')
(12, 'Lisa', 'Simmons')
(13, 'Jasmine', 'Mueller')
(14, 'Timothy', 'Patterson')
(15, 'Darren', 'Leonard')
(16, 'Rodney', 'Kim')
(17, 'Pamela', 'Wilcox')
(18, 'Jose', 'Rogers')
(19, 'Michael', 'Wallace')
(20, 'Carrie', 'Nguyen')
(21, 'Rebecca', 'Johnson')
(22, 'Daniel', 'Shannon')
(23, 'Dale', 'Mcdonald')
(24, 'Jorge', 'Mooney')
(25, 'Danielle', 'Fuentes')
(26, 'Carolyn', 'Shepherd')
(27, 'Travis', 'Parks')
(28, 'Christina', 'Sparks')
(29, 'Brian', 'Baldwin')
(30, 'Jo', 'Chan')
(31, 'George', 'Miller')
(32, 'Kevin', 'Robbins')
(33, 'Ryan', 'Peterson')
(34, 'Anne', 'Anderson')
(35, 'Steven', 'Thomas')
(36, 'Henry', 'Glover')
(37, 'Ashley', 'Barnes')
(38, 'John', 'Fisher')
(39, 'William', 'Roth')
(40, 'Christopher', 'Rodriguez')
(41, 'Kenneth', 'Mann')
(42, 'Jose', 'Anderson')
(43, 'Christopher', 'Miller')
(44, 'Nicole', 'Davis')
(45, 'Ashley', 'Alvarado')
(46, 'Kathy', 'Herring')
(47, 'Joy', 'Hobbs')
(48, 'William', 'Lawrence')
(49, 'Brian', 'Rodriguez')
(50, 'Brandon', 'Martin')
(51, 'Ricky', 'Peters')
(52, 'Jeffrey', 'Rogers')
(53, 'Candace', 'Barajas')
(54, 'Lee', 'Huynh')
(55, 'Laura', 'Farmer')
(56, 'Michael', 'Herring')
(57, 'Caitlyn', 'Thompson')
(58, 'Kimberly', 'Harper')
(59, 'Jessica', 'Williams')
(60, 'Tommy', 'Simmons')
(61, 'Sheila', 'Bell')
(62, 'Brandon', 'Perez')
(63, 'Kevin', 'Collier')
(64, 'Angela', 'Evans')
(65, 'Xavier', 'Johnson')
(66, 'Stacy', 'Frost')
(67, 'Nancy', 'Jones')
(68, 'Joseph', 'Drake')
(69, 'Francisco', 'Sanford')
(70, 'Stephanie', 'Gonzalez')
(71, 'Linda', 'White')
(72, 'Thomas', 'Douglas')
(73, 'Catherine', 'Williams')
(74, 'Maurice', 'Martin')
(75, 'James', 'Evans')
(76, 'Austin', 'Garcia')
(77, 'Drew', 'Cooper')
(78, 'Brittany', 'Cunningham')
(79, 'Amanda', 'Nelson')
(80, 'Bryan', 'Fields')
(81, 'Rebecca', 'Dyer')
(82, 'Gabriel', 'Green')
(83, 'Alejandra', 'Fernandez')
(84, 'Leonard', 'Clayton')
(85, 'Troy', 'Thomas')
(86, 'Kristina', 'Solomon')
(87, 'Courtney', 'Robbins')
(88, 'Joseph', 'Clark')
(89, 'Leah', 'Wright')
(90, 'Haley', 'Williams')